local KeyCode = Enum.KeyCode
return {
	[0x01] = nil, --Left mouse button
	[0x02] = nil, --Right mouse button
	[0x03] = nil, --Control-break processing
	[0x04] = nil, --Middle mouse button (three-button mouse)
	[0x05] = nil, --X1 mouse button
	[0x06] = nil, --X2 mouse button
	[0x07] = nil, --Undefined
	[0x08] = KeyCode.Backspace,
	[0x09] = KeyCode.Tab,
	[0x0A] = nil, --Reserved
	[0x0B] = nil, --Reserved
	[0x0C] = KeyCode.Clear,
	[0x0D] = KeyCode.Return,
	[0x0E] = nil, --Undefined
	[0x0F] = nil, --Undefined
	[0x10] = nil, --SHIFT key
	[0x11] = nil, --CTRL key
	[0x12] = nil, --ALT key
	[0x13] = KeyCode.Pause,
	[0x14] = KeyCode.CapsLock,
	[0x15] = nil, --IME Kana mode / IME Hanguel mode / IME Hangul mode
	[0x16] = nil, --IME On
	[0x17] = nil, --IME Junja mode
	[0x18] = nil, --IME final mode
	[0x19] = nil, --IME Hanja mode / IME Kanji mode
	[0x1A] = nil, --IME Off
	[0x1B] = KeyCode.Escape,
	[0x1C] = nil, --IME convert
	[0x1D] = nil, --IME nonconvert
	[0x1E] = nil, --IME accept
	[0x1F] = nil, --IME mode change request
	[0x20] = KeyCode.Space,
	[0x21] = KeyCode.PageUp,
	[0x22] = KeyCode.PageDown,
	[0x23] = KeyCode.End,
	[0x24] = KeyCode.Home,
	[0x25] = KeyCode.Left,
	[0x26] = KeyCode.Up,
	[0x27] = KeyCode.Right,
	[0x28] = KeyCode.Down,
	[0x29] = nil, --SELECT key
	[0x2A] = KeyCode.Print,
	[0x2B] = nil, --EXECUTE key
	[0x2C] = nil, --PRINT SCREEN key
	[0x2D] = KeyCode.Insert,
	[0x2E] = KeyCode.Delete,
	[0x2F] = KeyCode.Help,
	[0x30] = KeyCode.Zero,
	[0x31] = KeyCode.One,
	[0x32] = KeyCode.Two,
	[0x33] = KeyCode.Three,
	[0x34] = KeyCode.Four,
	[0x35] = KeyCode.Five,
	[0x36] = KeyCode.Six,
	[0x37] = KeyCode.Seven,
	[0x38] = KeyCode.Eight,
	[0x39] = KeyCode.Nine,
	[0x3A] = nil, --Undefined
	[0x3B] = nil, --Undefined
	[0x3C] = nil, --Undefined
	[0x3D] = nil, --Undefined
	[0x3E] = nil, --Undefined
	[0x3F] = nil, --Undefined
	[0x40] = nil, --Undefined
	[0x41] = KeyCode.A,
	[0x42] = KeyCode.B,
	[0x43] = KeyCode.C,
	[0x44] = KeyCode.D,
	[0x45] = KeyCode.E,
	[0x46] = KeyCode.F,
	[0x47] = KeyCode.G,
	[0x48] = KeyCode.H,
	[0x49] = KeyCode.I,
	[0x4A] = KeyCode.J,
	[0x4B] = KeyCode.K,
	[0x4C] = KeyCode.L,
	[0x4D] = KeyCode.M,
	[0x4E] = KeyCode.N,
	[0x4F] = KeyCode.O,
	[0x50] = KeyCode.P,
	[0x51] = KeyCode.Q,
	[0x52] = KeyCode.R,
	[0x53] = KeyCode.S,
	[0x54] = KeyCode.T,
	[0x55] = KeyCode.U,
	[0x56] = KeyCode.V,
	[0x57] = KeyCode.W,
	[0x58] = KeyCode.X,
	[0x59] = KeyCode.Y,
	[0x5A] = KeyCode.Z,
	[0x5B] = KeyCode.LeftSuper,
	[0x5C] = KeyCode.RightSuper,
	[0x5D] = nil, --Applications key (Natural keyboard)
	[0x5E] = nil, --Reserved
	[0x5F] = nil, --Computer Sleep key
	[0x60] = KeyCode.KeypadZero,
	[0x61] = KeyCode.KeypadOne,
	[0x62] = KeyCode.KeypadTwo,
	[0x63] = KeyCode.KeypadThree,
	[0x64] = KeyCode.KeypadFour,
	[0x65] = KeyCode.KeypadFive,
	[0x66] = KeyCode.KeypadSix,
	[0x67] = KeyCode.KeypadSeven,
	[0x68] = KeyCode.KeypadEight,
	[0x69] = KeyCode.KeypadNine,
	[0x6A] = KeyCode.KeypadMultiply,
	[0x6B] = KeyCode.KeypadPlus,
	[0x6C] = nil, --Separator key
	[0x6D] = KeyCode.KeypadMinus,
	[0x6E] = KeyCode.KeypadPeriod,
	[0x6F] = KeyCode.KeypadDivide,
	[0x70] = KeyCode.F1,
	[0x71] = KeyCode.F2,
	[0x72] = KeyCode.F3,
	[0x73] = KeyCode.F4,
	[0x74] = KeyCode.F5,
	[0x75] = KeyCode.F6,
	[0x76] = KeyCode.F7,
	[0x77] = KeyCode.F8,
	[0x78] = KeyCode.F9,
	[0x79] = KeyCode.F10,
	[0x7A] = KeyCode.F11,
	[0x7B] = KeyCode.F12,
	[0x7C] = KeyCode.F13,
	[0x7D] = KeyCode.F14,
	[0x7E] = KeyCode.F15,
	[0x7F] = nil, --F16 key
	[0x80] = nil, --F17 key
	[0x81] = nil, --F18 key
	[0x82] = nil, --F19 key
	[0x83] = nil, --F20 key
	[0x84] = nil, --F21 key
	[0x85] = nil, --F22 key
	[0x86] = nil, --F23 key
	[0x87] = nil, --F24 key
	[0x88] = nil, --Unassigned
	[0x89] = nil, --Unassigned
	[0x8A] = nil, --Unassigned
	[0x8B] = nil, --Unassigned
	[0x8C] = nil, --Unassigned
	[0x8D] = nil, --Unassigned
	[0x8E] = nil, --Unassigned
	[0x8F] = nil, --Unassigned
	[0x90] = KeyCode.NumLock,
	[0x91] = KeyCode.ScrollLock,
	[0x92] = nil, --OEM specific
	[0x93] = nil, --OEM specific
	[0x94] = nil, --OEM specific
	[0x95] = nil, --OEM specific
	[0x96] = nil, --OEM specific
	[0x97] = nil, --Unassigned
	[0x98] = nil, --Unassigned
	[0x99] = nil, --Unassigned
	[0x9A] = nil, --Unassigned
	[0x9B] = nil, --Unassigned
	[0x9C] = nil, --Unassigned
	[0x9D] = nil, --Unassigned
	[0x9E] = nil, --Unassigned
	[0x9F] = nil, --Unassigned
	[0xA0] = KeyCode.LeftShift,
	[0xA1] = KeyCode.RightShift,
	[0xA2] = KeyCode.LeftControl,
	[0xA3] = KeyCode.RightControl,
	[0xA4] = KeyCode.LeftAlt,
	[0xA5] = KeyCode.RightAlt,
	[0xA6] = nil, --Browser Back key
	[0xA7] = nil, --Browser Forward key
	[0xA8] = nil, --Browser Refresh key
	[0xA9] = nil, --Browser Stop key
	[0xAA] = nil, --Browser Search key
	[0xAB] = nil, --Browser Favorites key
	[0xAC] = nil, --Browser Start and Home key
	[0xAD] = nil, --Volume Mute key
	[0xAE] = nil, --Volume Down key
	[0xAF] = nil, --Volume Up key
	[0xB0] = nil, --Next Track key
	[0xB1] = nil, --Previous Track key
	[0xB2] = nil, --Stop Media key
	[0xB3] = nil, --Play/Pause Media key
	[0xB4] = nil, --Start Mail key
	[0xB5] = nil, --Select Media key
	[0xB6] = nil, --Start Application 1 key
	[0xB7] = nil, --Start Application 2 key
	[0xB8] = nil, --Reserved
	[0xB9] = nil, --Reserved
	[0xBA] = KeyCode.Semicolon,
	[0XBB] = KeyCode.Plus,
	[0xBC] = KeyCode.Comma,
	[0xBD] = KeyCode.Minus,
	[0xBE] = KeyCode.Period,
	[0xBF] = KeyCode.Slash,
	[0xC0] = KeyCode.Backquote,
	[0xC1] = nil, --Reserved
	[0xC2] = nil, --Reserved
	[0xC3] = nil, --Reserved
	[0xC4] = nil, --Reserved
	[0xC5] = nil, --Reserved
	[0xC6] = nil, --Reserved
	[0xC7] = nil, --Reserved
	[0xC8] = nil, --Reserved
	[0xC9] = nil, --Reserved
	[0xCA] = nil, --Reserved
	[0xCB] = nil, --Reserved
	[0xCC] = nil, --Reserved
	[0xCD] = nil, --Reserved
	[0xCE] = nil, --Reserved
	[0xCF] = nil, --Reserved
	[0xD0] = nil, --Reserved
	[0xD1] = nil, --Reserved
	[0xD2] = nil, --Reserved
	[0xD3] = nil, --Reserved
	[0xD4] = nil, --Reserved
	[0xD5] = nil, --Reserved
	[0xD6] = nil, --Reserved
	[0xD7] = nil, --Reserved
	[0xD8] = nil, --Unassigned
	[0xD9] = nil, --Unassigned
	[0xDA] = nil, --Unassigned
	[0xDB] = KeyCode.LeftBracket,
	[0xDC] = KeyCode.BackSlash,
	[0xDD] = KeyCode.RightBracket,
	[0xDE] = KeyCode.Quote,
	[0xDF] = nil, --Used for miscellaneous characters; it can vary by keyboard.
	[0xE0] = nil, --Reserved
	[0xE1] = nil, --OEM specific
	[0xE2] = nil, --The `<>` keys on the US standard keyboard, or the `\\\\|` key on the non-US 102-key keyboard
	[0xE3] = nil, --OEM specific
	[0xE4] = nil, --OEM specific
	[0xE5] = nil, --IME PROCESS key
	[0xE6] = nil, --OEM specific
	[0xE7] = nil, --Used to pass Unicode characters as if they were keystrokes.
	[0xE8] = nil, --Unassigned
	[0xE9] = nil, --OEM specific
	[0xEA] = nil, --OEM specific
	[0xEB] = nil, --OEM specific
	[0xEC] = nil, --OEM specific
	[0xED] = nil, --OEM specific
	[0xEE] = nil, --OEM specific
	[0xEF] = nil, --OEM specific
	[0xF0] = nil, --OEM specific
	[0xF1] = nil, --OEM specific
	[0xF2] = nil, --OEM specific
	[0xF3] = nil, --OEM specific
	[0xF4] = nil, --OEM specific
	[0xF5] = nil, --OEM specific
	[0xF6] = nil, --Attn key
	[0xF7] = nil, --CrSel key
	[0xF8] = nil, --ExSel key
	[0xF9] = nil, --Erase EOF key
	[0xFA] = nil, --Play key
	[0xFB] = nil, --Zoom key
	[0xFC] = nil, --Reserved
	[0xFD] = nil, --PA1 key
	[0xFE] = KeyCode.Clear --Clear key
}